//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace busbookingwebsite
{
    public partial class Book_now : System.Web.UI.Page
    {
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// txtBusName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtBusName;

        /// <summary>
        /// txtRoute control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtRoute;

        /// <summary>
        /// txtTravelDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtTravelDate;

        /// <summary>
        /// rfvTravelDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTravelDate;

        /// <summary>
        /// txtDepTime control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtDepTime;

        /// <summary>
        /// txtArrTime control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtArrTime;

        /// <summary>
        /// txtFarePerTicket control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtFarePerTicket;

        /// <summary>
        /// txtPassengerName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtPassengerName;

        /// <summary>
        /// rfvPassengerName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvPassengerName;

        /// <summary>
        /// txtAge control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtAge;

        /// <summary>
        /// rfvAge control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvAge;

        /// <summary>
        /// rvAge control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RangeValidator rvAge;

        /// <summary>
        /// ddlGender control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlGender;

        /// <summary>
        /// rfvGender control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvGender;

        /// <summary>
        /// txtContact control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtContact;

        /// <summary>
        /// rfvContact control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvContact;

        /// <summary>
        /// revContact control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revContact;

        /// <summary>
        /// txtEmail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        /// <summary>
        /// rfvEmail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvEmail;

        /// <summary>
        /// revEmail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revEmail;

        /// <summary>
        /// txtNumSeats control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtNumSeats;

        /// <summary>
        /// rfvNumSeats control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvNumSeats;

        /// <summary>
        /// rvNumSeats control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RangeValidator rvNumSeats;

        /// <summary>
        /// chkUseSeatLayout control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox chkUseSeatLayout;

        /// <summary>
        /// chkSeats control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBoxList chkSeats;

        /// <summary>
        /// btnConfirmPay control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnConfirmPay;

        /// <summary>
        /// btnCancel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnCancel;

        // Passenger 1 Controls
        protected global::System.Web.UI.WebControls.TextBox txtPassengerName1;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvPassengerName1;
        protected global::System.Web.UI.WebControls.TextBox txtAge1;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvAge1;
        protected global::System.Web.UI.WebControls.RangeValidator rvAge1;
        protected global::System.Web.UI.WebControls.DropDownList ddlGender1;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvGender1;
        protected global::System.Web.UI.WebControls.TextBox txtContact1;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvContact1;
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revContact1;
        protected global::System.Web.UI.WebControls.TextBox txtEmail1;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvEmail1;
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revEmail1;

        // Passenger 2 Controls
        protected global::System.Web.UI.WebControls.TextBox txtPassengerName2;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvPassengerName2;
        protected global::System.Web.UI.WebControls.TextBox txtAge2;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvAge2;
        protected global::System.Web.UI.WebControls.RangeValidator rvAge2;
        protected global::System.Web.UI.WebControls.DropDownList ddlGender2;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvGender2;
        protected global::System.Web.UI.WebControls.TextBox txtContact2;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvContact2;
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revContact2;
        protected global::System.Web.UI.WebControls.TextBox txtEmail2;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvEmail2;
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revEmail2;

        // Passenger 3 Controls
        protected global::System.Web.UI.WebControls.TextBox txtPassengerName3;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvPassengerName3;
        protected global::System.Web.UI.WebControls.TextBox txtAge3;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvAge3;
        protected global::System.Web.UI.WebControls.RangeValidator rvAge3;
        protected global::System.Web.UI.WebControls.DropDownList ddlGender3;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvGender3;
        protected global::System.Web.UI.WebControls.TextBox txtContact3;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvContact3;
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revContact3;
        protected global::System.Web.UI.WebControls.TextBox txtEmail3;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvEmail3;
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revEmail3;
    }
}
